service: lambda-post

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  apiHandler:
    handler: handler.api
    events:
      - http:
          path: specie
          method: POST
          cors: true
      - http:
          path: vehicle
          method: POST
          cors: true

